import ZIM, { ZIMError, ZIMEventHandler, ZIMEventOfBlacklistChangedResult, ZIMEventOfCallInvitationAcceptedResult, ZIMEventOfCallInvitationCancelledResult, ZIMEventOfCallInvitationCreatedResult, ZIMEventOfCallInvitationEndedResult, ZIMEventOfCallInvitationReceivedResult, ZIMEventOfCallInvitationRejectedResult, ZIMEventOfCallInvitationTimeoutResult, ZIMEventOfCallInviteesAnsweredTimeoutResult, ZIMEventOfCallUserStateChangedResult, ZIMEventOfConnectionStateChangedResult, ZIMEventOfConversationChangedResult, ZIMEventOfConversationsAllDeletedResult, ZIMEventOfConversationTotalUnreadMessageCountUpdatedResult, ZIMEventOfFriendApplicationListChangedResult, ZIMEventOfFriendApplicationUpdatedResult, ZIMEventOfFriendInfoUpdatedResult, ZIMEventOfFriendListChangedResult, ZIMEventOfGroupApplicationListChangedResult, ZIMEventOfGroupApplicationUpdatedResult, ZIMEventOfGroupAttributesUpdatedResult, ZIMEventOfGroupAvatarUrlUpdatedResult, ZIMEventOfGroupMemberInfoUpdatedResult, ZIMEventOfGroupMemberStateChangedResult, ZIMEventOfGroupMutedInfoUpdatedResult, ZIMEventOfGroupNameUpdatedResult, ZIMEventOfGroupNoticeUpdatedResult, ZIMEventOfGroupStateChangedResult, ZIMEventOfGroupVerifyInfoUpdatedResult, ZIMEventOfMessageDeletedResult, ZIMEventOfMessageReactionsChangedResult, ZIMEventOfMessageReceiptChangedResult, ZIMEventOfMessageRevokeReceivedResult, ZIMEventOfMessageSentStatusChangedResult, ZIMEventOfReceiveConversationMessageResult, ZIMEventOfRoomAttributesUpdatedResult, ZIMEventOfRoomMemberChangedResult, ZIMEventOfRoomMembersAttributesUpdatedResult, ZIMEventOfRoomStateChangedResult, ZIMEventOfTokenWillExpireResult, ZIMEventOfUserInfoUpdatedResult, ZIMEventOfUserRuleUpdatedResult } from "./ZIMUniApp";
export declare class DefaultZIMEventHandler implements Partial<ZIMEventHandler> {
    handler?: Partial<ZIMEventHandler>;
    constructor(handler?: Partial<ZIMEventHandler>);
    error(zim: ZIM, errorInfo: ZIMError): void;
    connectionStateChanged(zim: ZIM, data: ZIMEventOfConnectionStateChangedResult): void;
    tokenWillExpire(zim: ZIM, data: ZIMEventOfTokenWillExpireResult): void;
    userInfoUpdated(zim: ZIM, data: ZIMEventOfUserInfoUpdatedResult): void;
    userRuleUpdated(zim: ZIM, data: ZIMEventOfUserRuleUpdatedResult): void;
    conversationsAllDeleted(zim: ZIM, data: ZIMEventOfConversationsAllDeletedResult): void;
    conversationChanged(zim: ZIM, data: ZIMEventOfConversationChangedResult): void;
    conversationTotalUnreadMessageCountUpdated(zim: ZIM, data: ZIMEventOfConversationTotalUnreadMessageCountUpdatedResult): void;
    receivePeerMessage(zim: ZIM, data: ZIMEventOfReceiveConversationMessageResult): void;
    receiveGroupMessage(zim: ZIM, data: ZIMEventOfReceiveConversationMessageResult): void;
    receiveRoomMessage(zim: ZIM, data: ZIMEventOfReceiveConversationMessageResult): void;
    conversationMessageReceiptChanged(zim: ZIM, data: ZIMEventOfMessageReceiptChangedResult): void;
    messageReceiptChanged(zim: ZIM, data: ZIMEventOfMessageReceiptChangedResult): void;
    messageRevokeReceived(zim: ZIM, data: ZIMEventOfMessageRevokeReceivedResult): void;
    messageSentStatusChanged(zim: ZIM, data: ZIMEventOfMessageSentStatusChangedResult): void;
    messageReactionsChanged(zim: ZIM, data: ZIMEventOfMessageReactionsChangedResult): void;
    messageDeleted(zim: ZIM, data: ZIMEventOfMessageDeletedResult): void;
    roomStateChanged(zim: ZIM, data: ZIMEventOfRoomStateChangedResult): void;
    roomMemberJoined(zim: ZIM, data: ZIMEventOfRoomMemberChangedResult): void;
    roomMemberLeft(zim: ZIM, data: ZIMEventOfRoomMemberChangedResult): void;
    roomAttributesUpdated(zim: ZIM, data: ZIMEventOfRoomAttributesUpdatedResult): void;
    roomAttributesBatchUpdated(zim: ZIM, data: ZIMEventOfRoomAttributesUpdatedResult): void;
    roomMemberAttributesUpdated(zim: ZIM, data: ZIMEventOfRoomMembersAttributesUpdatedResult): void;
    groupStateChanged(zim: ZIM, data: ZIMEventOfGroupStateChangedResult): void;
    groupNameUpdated(zim: ZIM, data: ZIMEventOfGroupNameUpdatedResult): void;
    groupAvatarUrlUpdated(zim: ZIM, data: ZIMEventOfGroupAvatarUrlUpdatedResult): void;
    groupNoticeUpdated(zim: ZIM, data: ZIMEventOfGroupNoticeUpdatedResult): void;
    groupAttributesUpdated(zim: ZIM, data: ZIMEventOfGroupAttributesUpdatedResult): void;
    groupMemberStateChanged(zim: ZIM, data: ZIMEventOfGroupMemberStateChangedResult): void;
    groupMemberInfoUpdated(zim: ZIM, data: ZIMEventOfGroupMemberInfoUpdatedResult): void;
    groupMutedInfoUpdated(zim: ZIM, data: ZIMEventOfGroupMutedInfoUpdatedResult): void;
    groupVerifyInfoUpdated(zim: ZIM, data: ZIMEventOfGroupVerifyInfoUpdatedResult): void;
    groupApplicationListChanged(zim: ZIM, data: ZIMEventOfGroupApplicationListChangedResult): void;
    groupApplicationUpdated(zim: ZIM, data: ZIMEventOfGroupApplicationUpdatedResult): void;
    callInvitationCreated(zim: ZIM, data: ZIMEventOfCallInvitationCreatedResult): void;
    callInvitationReceived(zim: ZIM, data: ZIMEventOfCallInvitationReceivedResult): void;
    callInvitationCancelled(zim: ZIM, data: ZIMEventOfCallInvitationCancelledResult): void;
    callInvitationTimeout(zim: ZIM, data: ZIMEventOfCallInvitationTimeoutResult): void;
    callInvitationEnded(zim: ZIM, data: ZIMEventOfCallInvitationEndedResult): void;
    callUserStateChanged(zim: ZIM, data: ZIMEventOfCallUserStateChangedResult): void;
    callInvitationAccepted(zim: ZIM, data: ZIMEventOfCallInvitationAcceptedResult): void;
    callInvitationRejected(zim: ZIM, data: ZIMEventOfCallInvitationRejectedResult): void;
    callInviteesAnsweredTimeout(zim: ZIM, data: ZIMEventOfCallInviteesAnsweredTimeoutResult): void;
    blacklistChanged(zim: ZIM, data: ZIMEventOfBlacklistChangedResult): void;
    friendListChanged(zim: ZIM, data: ZIMEventOfFriendListChangedResult): void;
    friendInfoUpdated(zim: ZIM, data: ZIMEventOfFriendInfoUpdatedResult): void;
    friendApplicationListChanged(zim: ZIM, data: ZIMEventOfFriendApplicationListChangedResult): void;
    friendApplicationUpdated(zim: ZIM, data: ZIMEventOfFriendApplicationUpdatedResult): void;
}
