import { ZegoSignalingConnectionState, ZegoSignalingInRoomCommandMessage, ZegoSignalingInRoomTextMessage } from '../../plugins';
import { ZegoUIKitUser, ZegoUserInRoomAttributesInfo } from '../defines';
import { ZegoUIKitInvitationData, ZegoUIKitSignalingConnectionStateChangeListener, ZegoUIKitSignalingInRoomCommandMessageListener, ZegoUIKitSignalingInRoomTextMessageListener, ZegoUIKitSignalingInvitationListener, ZegoUIKitSignalingRoomPropertyUpdateListener, ZegoUIKitSignalingUsersInRoomAttributesUpdateListener } from './defines';
export declare class UIKitSignalingService {
    private invitationListenerList;
    private roomPropertyUpdateListenerList;
    private usersInRoomAttributesUpdateListenerList;
    private inRoomTextMessageListenerNotifyList;
    private inRoomCommandMessageListenerNotifyList;
    private connectionStateChangeListenerNotifyList;
    notifyCallInvitationReceived(inviter: ZegoUIKitUser, type: number, data: ZegoUIKitInvitationData): void;
    notifyCallInvitationCancelled(inviter: ZegoUIKitUser, data: ZegoUIKitInvitationData): void;
    notifyCallInvitationAccepted(invitee: ZegoUIKitUser, data: ZegoUIKitInvitationData): void;
    notifyCallInvitationRejected(invitee: ZegoUIKitUser, data: ZegoUIKitInvitationData): void;
    notifyCallInvitationTimeout(inviter: ZegoUIKitUser, data: ZegoUIKitInvitationData): void;
    notifyCallInviteesAnsweredTimeout(users: ZegoUIKitUser[], data: ZegoUIKitInvitationData): void;
    notifyCallingInvitationSend(invitees: ZegoUIKitUser[], data: ZegoUIKitInvitationData): void;
    notifyCancelInvitaion(invitees: ZegoUIKitUser[], data: ZegoUIKitInvitationData): void;
    notifyRoomPropertyUpdated(key: string, oldValue: string, newValue: string): void;
    notifyRoomPropertyFullUpdated(updateKeys: string[], oldRoomAttributes: Record<string, string>, roomAttributes: Record<string, string>): void;
    notifyUsersInRoomAttributesUpdated(updateKeys: string[], oldAttributes: ZegoUserInRoomAttributesInfo[], attributes: ZegoUserInRoomAttributesInfo[], editor: ZegoUIKitUser | null): void;
    addRoomPropertyUpdateListener(listenerID: string, listener: ZegoUIKitSignalingRoomPropertyUpdateListener): void;
    removeRoomPropertyUpdateListener(listenerID: string): void;
    addUsersInRoomAttributesUpdateListener(listenerID: string, listener: ZegoUIKitSignalingUsersInRoomAttributesUpdateListener): void;
    removeUsersInRoomAttributesUpdateListener(listenerID: string): void;
    addInvitationListener(listenerID: string, listener: ZegoUIKitSignalingInvitationListener): void;
    removeInvitationListener(listenerID: string): void;
    clear(): void;
    removeRoomListeners(): void;
    addInRoomTextMessageListener(listenerID: string, listener: ZegoUIKitSignalingInRoomTextMessageListener): void;
    removeInRoomTextMessageListener(listenerID: string): void;
    addInRoomCommandMessageListener(listenerID: string, listener: ZegoUIKitSignalingInRoomCommandMessageListener): void;
    removeInRoomCommandMessageListener(listenerID: string): void;
    notifyInRoomTextMessageReceived(messages: ZegoSignalingInRoomTextMessage[], roomID: string): void;
    addConnectionStateChangeListener(listenerID: string, listener: ZegoUIKitSignalingConnectionStateChangeListener): void;
    removeConnectionStateChangeListener(listenerID: string): void;
    notifyConnectionStateChange(connectionState: ZegoSignalingConnectionState): void;
    onInRoomCommandMessageReceived(messages: ZegoSignalingInRoomCommandMessage[], roomID: string): void;
}
